spring.application.name=nexacorp-ai-backend

spring.ai.openai.api-key=gsk_TwbTaG42EW3v0DWvCUqKWGdyb3FYZmZHsMkYYct7llMZHc3Y3a
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b


